# load zplug
[ -s "${HOME}/locale.sh" ] && source "${HOME}/locale.sh"

# specify plugins here

# Bundles from the default repo (robbyrussell's oh-my-zsh).
#zplug "plugins/git" from: oh-my-zsh
#zplug "plugins/git-extras" from: oh-my-zsh
zplug "plugins/docker" from:oh-my-zsh
zplug "plugins/tmux" from:oh-my-zsh

# Syntax highlighting bundle.
zplug "zsh-users/zsh-syntax-highlighting"
zplug "zsh-users/zsh-autosuggestions"
zplug "zsh-users/zsh-history-substring-search"

#zplug 'dracula/zsh', as:theme
#zplug load "themes/agnoster, from: oh-my-zsh"

# hide username@host in prompt
export default_user="$user"

alias docker-cc='docker rm $(docker ps -a -fstatus=exited -q)'
alias docker-ci='docker rmi $(docker images -f "dangling=true" -q)'
alias rg=rgrep

docker_debug() {
	docker commit $1 docker_debug/debug_image && docker run --rm -it docker_debug/debug_image /bin/bash
}
alias docker-debug=docker_debug

#find all changes to filename not merged to master:
alias ba_git_find_all_branches='git for-each-ref --format="%(refname:short)" refs/heads | grep -v master | while read br; do git cherry master $br | while read x h; do if [ \"`git log -n 1 --format=%h $h -- $filename`\" = \"$h\" ]; then echo $br; fi; done; done | sort -u'

alias gbg='LANG=C git branch -vv | grep ": gone\]"'
alias gbgD='LANG=C git branch --no-color -vv | grep ": gone\]" | cut -c 3- | awk '\''{print $1}'\'' | xargs git branch -D'
alias gbgd='LANG=C git branch --no-color -vv | grep ": gone\]" | cut -c 3- | awk '\''{print $1}'\'' | xargs git branch -d'
alias gl='git pull'
alias gp='git push'
alias gf='git fetch'

export history_ignore="ls *:cd *:pwd:exit::man*:env*:?:??:df *:du *"

function azp_git_on() {
    echo "injecting secret for internal server"
    B64=$(echo -n $USER:$(pass show ${INTERNAL_GIT_SERVER}/AZP_CODE_TOKEN) | base64 -w0 )
    export GIT_EXTRA_HEADER="Authorization: Basic $B64"
    alias git='git -c http.extraheader=$GIT_EXTRA_HEADER'
}

function azp_git(){

    if [[ $(git remote get-url --all origin | sed "s!https://${INTERNAL_GIT_SERVER}/.*!internal!") == "internal" ]]; then
        azp_git_on
    else
        alias git=git
        export AZP_CODE_TOKEN=
    fi
}

function ba_git_curl_debug(){
    if [[ -z "$GIT_CURL_VERBOSE" ]]; then
        echo "turning on git debugging"
        export GIT_CURL_VERBOSE=1
        export GIT_TRACE=1
    else
        echo "turning off git debugging"
        unset GIT_CURL_VERBOSE
        unset GIT_TRACE
    fi
}

[[ -s "$home/.local/share/marker/marker.sh" ]] && source "$home/.local/share/marker/marker.sh"
#[[ -f '/usr/share/powerline/bindings/zsh/powerline.zsh' ]] && source /usr/share/powerline/bindings/zsh/powerline.zsh
#
# Install plugins if there are plugins that have not been installed
if ! zplug check --verbose; then
    printf "Install? [y/N]: "
    if read -q; then
        echo; zplug install
    fi
fi

# Then, source plugins and add commands to $PATH
zplug load --verbose
